### ISSUE TITLE
Liquid syntax error

### ISSUE THREAD

**Issue by yingziwu** [jaehee0113/console#3]
## Run "jekyll new"

```
$ jekyll new yingziwu.github.io
Running bundle install in /home/arch/Documents/userful/blog/yingziwu.github.io...
  Bundler: The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x86-mswin32, x64-mingw32, java. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x86-mswin32 x64-mingw32 java`.
  Bundler: Fetching gem metadata from https://rubygems.org/............
  Bundler: Fetching version metadata from https://rubygems.org/...
  Bundler: Fetching dependency metadata from https://rubygems.org/..
  Bundler: Resolving dependencies...
  Bundler: Using public_suffix 2.0.5
  Bundler: Using colorator 1.1.0
  Bundler: Using ffi 1.9.18
  Bundler: Using forwardable-extended 2.6.0
  Bundler: Using sass 3.4.23
  Bundler: Using rb-fsevent 0.9.8
  Bundler: Using kramdown 1.13.2
  Bundler: Using liquid 3.0.6
  Bundler: Using mercenary 0.3.6
  Bundler: Using rouge 1.11.1
  Bundler: Using safe_yaml 1.0.4
  Bundler: Using bundler 1.14.6
  Bundler: Using addressable 2.5.1
  Bundler: Using rb-inotify 0.9.8
  Bundler: Using pathutil 0.14.0
  Bundler: Using jekyll-sass-converter 1.5.0
  Bundler: Using listen 3.0.8
  Bundler: Using jekyll-watch 1.5.0
  Bundler: Using jekyll 3.4.3
  Bundler: Using jekyll-feed 0.9.2
  Bundler: Using minima 2.1.1
  Bundler: Bundle complete! 4 Gemfile dependencies, 21 gems now installed.
  Bundler: Use `bundle show [gemname]` to see where a bundled gem is installed.
New jekyll site installed in /home/arch/Documents/userful/blog/yingziwu.github.io.
```

## Modify "Gemfile"

```
$ cat Gemfile
source "https://rubygems.org"
ruby RUBY_VERSION

# Hello! This is where you manage which Jekyll version is used to run.
# When you want to use a different version, change it below, save the
# file and run `bundle install`. Run Jekyll with `bundle exec`, like so:
#
#     bundle exec jekyll serve
#
# This will help ensure the proper Jekyll version is running.
# Happy Jekylling!
gem "jekyll", "3.4.3"

# This is the default theme for new Jekyll sites. You may change this to anything you like.
gem "minima", "~> 2.0"
gem "console-theme"

# If you want to use GitHub Pages, remove the "gem "jekyll"" above and
# uncomment the line below. To upgrade, run `bundle update github-pages`.
# gem "github-pages", group: :jekyll_plugins

# If you have any plugins, put them here!
group :jekyll_plugins do
   gem "jekyll-feed", "~> 0.6"
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
```
## Modify "_config.yml"

```
cat _config.yml                             ~/Documents/userful/blog/yingziwu.github.io.backup
# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Your awesome title
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
theme: console-theme
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
```
## Run "bundle"

```
$ bundle
The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x86-mswin32, x64-mingw32, java. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x86-mswin32 x64-mingw32 java`.
Fetching gem metadata from https://rubygems.org/............
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rubygems.org/..
Resolving dependencies...
Using public_suffix 2.0.5
Using colorator 1.1.0
Using sass 3.4.23
Using rb-fsevent 0.9.8
Using ffi 1.9.18
Using kramdown 1.13.2
Using liquid 3.0.6
Using mercenary 0.3.6
Using forwardable-extended 2.6.0
Using rouge 1.11.1
Using safe_yaml 1.0.4
Using bundler 1.14.6
Using addressable 2.5.1
Using jekyll-sass-converter 1.5.0
Using rb-inotify 0.9.8
Using pathutil 0.14.0
Using listen 3.0.8
Using jekyll-watch 1.5.0
Using jekyll 3.4.3
Installing console-theme 1.0.1
Using jekyll-feed 0.9.2
Using minima 2.1.1
Bundle complete! 5 Gemfile dependencies, 22 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
```
## Where is package.json ?

I could't find the package.json .

```
$ ls -l
total 24
-rw-r--r-- 1 arch arch  525 Apr 20 21:07 about.md
-rw-r--r-- 1 arch arch 1409 Apr 20 21:43 _config.yml
-rw-r--r-- 1 arch arch  972 Apr 20 21:44 Gemfile
-rw-r--r-- 1 arch arch 1242 Apr 20 21:11 Gemfile.lock
-rw-r--r-- 1 arch arch  213 Apr 20 21:07 index.md
drwxr-xr-x 3 arch arch 4096 Apr 20 21:20 _posts
```

```
$ pwd
/home/arch/.gem/ruby/2.4.0/gems/console-theme-1.0.1
$ ls *
LICENSE.txt  README.md

assets:
css  images  js

_includes:
category.html  footer.html  header.html  home.html        not_found.html
comment.html   global.html  head.html    navigation.html  search.html

_layouts:
category.html  default.html  home.html  main.html  page.html  post.html  search.html

node_modules:

_sass:
_blocks  _configurations  _mixins  style.scss
```
## Try run "jekyll serve"

```
$ bundle exec jekyll serve
Configuration file: /home/arch/Documents/userful/blog/yingziwu.github.io/_config.yml
Configuration file: /home/arch/Documents/userful/blog/yingziwu.github.io/_config.yml
            Source: /home/arch/Documents/userful/blog/yingziwu.github.io
       Destination: /home/arch/Documents/userful/blog/yingziwu.github.io/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
  Liquid Exception: Liquid syntax error (line 12): Unknown tag 'localize' in /home/arch/.gem/ruby/2.4.0/gems/console-theme-1.0.1/_includes/head.html, included in /_layouts/post.html
jekyll 3.4.3 | Error:  Liquid syntax error (line 12): Unknown tag 'localize'
```

**Comment by jaehee0113** [comment]
I see the issue. Sorry, I haven't been making the master branch up to date. I will do it asap. for package.json, I don't know why it was excluded but one of the feature branches will have that file and you can tentatively download the file from that branch.

When running jekyll serve, I can see that it doesn't recognize the tag 'localize.' Would you please make sure that localize.rb is in your _plugins folder? Basically, the Liquid template engine should load every plugin inside that folder and be available as soon as you run 'bundle exec jekyll serve.'

**Comment by jaehee0113** [comment]
I just tested and it is working fine. Make sure to checkout the master branch (which is by default) and then first run npm install -i to install dependencies, then run gulp to make sure to build files. After that you might consider using 'bundle exec jekyll serve' to see the website being correctly displayed on your local first. Let me know if you experience difficulties. If not, this issue will be closed in 7 days.

**Comment by yingziwu** [comment]
A little mistake.

After replace `jekyll` with `bundle exec jekyll`, everything is ok.

Error log:
```
$ ./node_modules/.bin/gulp
[15:28:39] Using gulpfile ~/Documents/myblog/console/gulpfile.js
[15:28:39] Starting 'jsonSass'...
[15:28:39] Starting 'sass'...
[15:28:39] Starting 'bundle'...
[15:28:39] Finished 'bundle' after 652 μs
[15:28:39] Starting 'minify-js'...
[15:28:39] Starting 'jekyll-build'...
[15:28:39] Starting 'watch'...
[15:28:39] Finished 'watch' after 33 ms
[15:28:39] Starting 'js/client.js'...
[15:28:39] Finished 'js/client.js' after 3.95 ms
[15:28:39] Starting 'css/style.css'...
[15:28:39] Finished 'css/style.css' after 5.04 ms
WARN: Unresolved specs during Gem::Specification.reset:
      listen (< 3.1, ~> 3.0)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
/home/arch/.gem/ruby/2.4.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:40:in `block in setup': You have already activated jekyll 3.4.3, but your Gemfile requires jekyll 3.3.1. Prepending `bundle exec` to your command may solve this. (Gem::LoadError)
        from /usr/lib/ruby/2.4.0/forwardable.rb:229:in `each'
        from /usr/lib/ruby/2.4.0/forwardable.rb:229:in `each'
        from /home/arch/.gem/ruby/2.4.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:25:in `map'
        from /home/arch/.gem/ruby/2.4.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:25:in `setup'
        from /home/arch/.gem/ruby/2.4.0/gems/bundler-1.14.6/lib/bundler.rb:100:in `setup'
        from /home/arch/.gem/ruby/2.4.0/gems/jekyll-3.4.3/lib/jekyll/plugin_manager.rb:36:in `require_from_bundler'
        from /home/arch/.gem/ruby/2.4.0/gems/jekyll-3.4.3/exe/jekyll:9:in `<top (required)>'
        from /home/arch/.gem/ruby/2.4.0/bin/jekyll:22:in `load'
        from /home/arch/.gem/ruby/2.4.0/bin/jekyll:22:in `<main>'
[15:28:40] 'jekyll-build' errored after 610 ms
[15:28:40] Error: 1
    at formatError (/home/arch/Documents/myblog/console/node_modules/gulp/bin/gulp.js:169:10)
    at Gulp.<anonymous> (/home/arch/Documents/myblog/console/node_modules/gulp/bin/gulp.js:195:15)
    at emitOne (events.js:96:13)
    at Gulp.emit (events.js:191:7)
    at Gulp.Orchestrator._emitTaskDone (/home/arch/Documents/myblog/console/node_modules/orchestrator/index.js:264:8)
    at /home/arch/Documents/myblog/console/node_modules/orchestrator/index.js:275:23
    at finish (/home/arch/Documents/myblog/console/node_modules/orchestrator/lib/runTask.js:21:8)
    at ChildProcess.cb (/home/arch/Documents/myblog/console/node_modules/orchestrator/lib/runTask.js:29:3)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
[15:28:40] Finished 'jsonSass' after 631 ms
[15:28:40] Finished 'sass' after 621 ms
[15:28:40] Finished 'minify-js' after 614 ms
[15:28:40] Starting 'sass'...
[15:28:40] Starting 'jekyll-build'...
[15:28:40] Starting 'minify-js'...
[15:28:40] Finished 'minify-js' after 352 ms
[15:28:40] Finished 'sass' after 362 ms
[15:28:40] Starting 'minify-css'...
[15:28:40] Finished 'minify-css' after 146 ms
WARN: Unresolved specs during Gem::Specification.reset:
      listen (< 3.1, ~> 3.0)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
/home/arch/.gem/ruby/2.4.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:40:in `block in setup': You have already activated jekyll 3.4.3, but your Gemfile requires jekyll 3.3.1. Prepending `bundle exec` to your command may solve this. (Gem::LoadError)
        from /usr/lib/ruby/2.4.0/forwardable.rb:229:in `each'
        from /usr/lib/ruby/2.4.0/forwardable.rb:229:in `each'
        from /home/arch/.gem/ruby/2.4.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:25:in `map'
        from /home/arch/.gem/ruby/2.4.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:25:in `setup'
        from /home/arch/.gem/ruby/2.4.0/gems/bundler-1.14.6/lib/bundler.rb:100:in `setup'
        from /home/arch/.gem/ruby/2.4.0/gems/jekyll-3.4.3/lib/jekyll/plugin_manager.rb:36:in `require_from_bundler'
        from /home/arch/.gem/ruby/2.4.0/gems/jekyll-3.4.3/exe/jekyll:9:in `<top (required)>'
        from /home/arch/.gem/ruby/2.4.0/bin/jekyll:22:in `load'
        from /home/arch/.gem/ruby/2.4.0/bin/jekyll:22:in `<main>'
[15:28:40] 'jekyll-build' errored after 576 ms
[15:28:40] Error: 1
    at formatError (/home/arch/Documents/myblog/console/node_modules/gulp/bin/gulp.js:169:10)
    at Gulp.<anonymous> (/home/arch/Documents/myblog/console/node_modules/gulp/bin/gulp.js:195:15)
    at emitOne (events.js:96:13)
    at Gulp.emit (events.js:191:7)
    at Gulp.Orchestrator._emitTaskDone (/home/arch/Documents/myblog/console/node_modules/orchestrator/index.js:264:8)
    at /home/arch/Documents/myblog/console/node_modules/orchestrator/index.js:275:23
    at finish (/home/arch/Documents/myblog/console/node_modules/orchestrator/lib/runTask.js:21:8)
    at ChildProcess.cb (/home/arch/Documents/myblog/console/node_modules/orchestrator/lib/runTask.js:29:3)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
[15:28:40] Starting 'sass'...
[15:28:40] Starting 'jekyll-build'...
[15:28:40] Finished 'sass' after 34 ms
[15:28:40] Starting 'minify-css'...
[15:28:40] Finished 'minify-css' after 50 ms
WARN: Unresolved specs during Gem::Specification.reset:
      listen (< 3.1, ~> 3.0)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
/home/arch/.gem/ruby/2.4.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:40:in `block in setup': You have already activated jekyll 3.4.3, but your Gemfile requires jekyll 3.3.1. Prepending `bundle exec` to your command may solve this. (Gem::LoadError)
        from /usr/lib/ruby/2.4.0/forwardable.rb:229:in `each'
        from /usr/lib/ruby/2.4.0/forwardable.rb:229:in `each'
        from /home/arch/.gem/ruby/2.4.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:25:in `map'
        from /home/arch/.gem/ruby/2.4.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:25:in `setup'
        from /home/arch/.gem/ruby/2.4.0/gems/bundler-1.14.6/lib/bundler.rb:100:in `setup'
        from /home/arch/.gem/ruby/2.4.0/gems/jekyll-3.4.3/lib/jekyll/plugin_manager.rb:36:in `require_from_bundler'
        from /home/arch/.gem/ruby/2.4.0/gems/jekyll-3.4.3/exe/jekyll:9:in `<top (required)>'
        from /home/arch/.gem/ruby/2.4.0/bin/jekyll:22:in `load'
        from /home/arch/.gem/ruby/2.4.0/bin/jekyll:22:in `<main>'
[15:28:41] 'jekyll-build' errored after 544 ms
[15:28:41] Error: 1
    at formatError (/home/arch/Documents/myblog/console/node_modules/gulp/bin/gulp.js:169:10)
    at Gulp.<anonymous> (/home/arch/Documents/myblog/console/node_modules/gulp/bin/gulp.js:195:15)
    at emitOne (events.js:96:13)
    at Gulp.emit (events.js:191:7)
    at Gulp.Orchestrator._emitTaskDone (/home/arch/Documents/myblog/console/node_modules/orchestrator/index.js:264:8)
    at /home/arch/Documents/myblog/console/node_modules/orchestrator/index.js:275:23
    at finish (/home/arch/Documents/myblog/console/node_modules/orchestrator/lib/runTask.js:21:8)
    at ChildProcess.cb (/home/arch/Documents/myblog/console/node_modules/orchestrator/lib/runTask.js:29:3)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
^C
```

git diff gulpfile.js
```
diff --git a/gulpfile.js b/gulpfile.js
index 1dbc806..1e38c87 100644
--- a/gulpfile.js
+++ b/gulpfile.js
@@ -16,7 +16,7 @@ var gulp = require('gulp'),
   sourcemaps = require('gulp-sourcemaps'),
   plumber = require('gulp-plumber')
   cp = require('child_process'),
-  jekyllCommand = (/^win/.test(process.platform)) ? 'jekyll.bat' : 'jekyll';
+  jekyllCommand = (/^win/.test(process.platform)) ? 'jekyll.bat' : 'bundle exec jekyll';

 //Bundling js / css
 gulp.task('bundle', function(){
```

**Comment by jaehee0113** [comment]
would you consider creating a pull request for this error fix? thanks.
